"""Audit the photo-refund judge. One command, four clues.

    python examples/photo_refund/run_audit.py
    python examples/photo_refund/run_audit.py --clue 2

This is the talk, in a terminal. Each clue prints what a normal eval report
would have told you, then what the audit finds.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import pandas as pd

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from judge_audit import metrics as M  # noqa: E402
from judge_audit import report as R  # noqa: E402

HERE = pathlib.Path(__file__).parent
THRESHOLD = 7.0


def load() -> pd.DataFrame:
    path = HERE / "judged.csv"
    if not path.exists():
        raise SystemExit(
            "judged.csv is missing -- run:  python examples/photo_refund/make_data.py")
    df = pd.read_csv(path)
    return df.rename(columns={"order_id": "item_id", "photo_clarity": "difficulty_stratum"})


def clue_1(df: pd.DataFrame) -> None:
    R.act(1, "Same photo, different score",
          "The judge scored every refund decision three times. Same trace, same prompt.")
    rep = M.stability(df, threshold=THRESHOLD)
    R.table(rep.as_rows())
    R.verdict(rep.exact_agreement > 0.9,
              f"{rep.exact_agreement:.0%} of orders got the same score all three times, and "
              f"{rep.flip_rate_at_threshold:.0%} changed pass/fail between passes")
    R.takeaway("If you scored these once, a quarter of your pass/fail labels were a coin "
               "flip. Run three passes and publish the spread.")


def clue_2(df: pd.DataFrame) -> None:
    R.act(2, "The orders the judge never scored",
          "Blank, unparseable, refused. They are not missing at random.")
    miss = M.missingness(df)
    R.table(miss.as_rows())
    print()
    R.frame(M.stratified(df))
    R.takeaway("The judge goes quiet on the confusing photos -- and those are the ones "
               "you needed it for. Retry the blanks and publish the number you get after.")


def clue_3(df: pd.DataFrame) -> None:
    R.act(3, "Agreement that counts lucky guesses",
          "Most refund calls are easy, and everyone says 'fine' a lot.")
    per_order = df.groupby("item_id").agg(
        judge=("judge_score_recovered", "mean"), human=("human_score", "first"))
    rep = M.agreement(per_order["judge"], per_order["human"], threshold=THRESHOLD)
    R.table(rep.as_rows())
    R.takeaway("Report agreement after chance correction, with the always-guess baseline "
               "printed next to it.")


def clue_4(df: pd.DataFrame, *, fast: bool) -> None:
    R.act(4, "The confident wrong refund",
          "Well-reasoned, decisive, and the wrong call.")
    per_order = df.groupby("item_id").agg(
        graded_score=("judge_score_recovered", "mean"),
        graded_single_run=("judge_score", "first"),
        equivalent=("right_call", lambda s: bool(s.mean() >= 0.5)),
        human_correct=("human_correct", "first"),
        fluent_but_wrong=("fluent_but_wrong", "first"),
        system=("agent_version", "first"),
        human_score=("human_score", "first"),
    ).reset_index()
    rep = M.dual_judge(per_order, threshold=THRESHOLD)
    R.table(rep.as_rows())
    R.takeaway("A graded score answers 'was this handled well?'. Add a second judge that "
               "answers 'was it the right call?' and require both.")
    print()
    R.act("4b", "What it costs you",
          "Two agent versions. The judge has to name the better one.")
    risk = M.decision_risk(per_order, judge_col="graded_single_run",
                           n_items=100, n_bootstrap=400 if fast else 2000)
    R.table(risk.as_rows())
    R.takeaway("Nobody can act on a correlation. Everybody can act on 'at our eval size we "
               "name the wrong version one time in four'.")


CLUES = {1: clue_1, 2: clue_2, 3: clue_3, 4: clue_4}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--clue", type=int, choices=sorted(CLUES), action="append")
    ap.add_argument("--fast", action="store_true", help="fewer bootstrap replicates")
    args = ap.parse_args(argv)

    df = load()
    R.banner("SYNTHETIC ORDERS. No real customers, no real photos, no real model output -- "
             "the trace is generated by judge_audit.simulate and calibrated to published "
             "effect sizes. Point these same audits at your own judge output for real ones.")
    print()
    R.table([
        ("orders", f"{df['item_id'].nunique()}"),
        ("judge passes each", f"{df['run'].nunique()}"),
        ("agent versions compared", ", ".join(sorted(df['agent_version'].unique()))),
    ])

    for k in (args.clue or sorted(CLUES)):
        if k == 4:
            CLUES[k](df, fast=args.fast)
        else:
            CLUES[k](df)
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
