"""A judge simulator, for a demo that has to run in a conference room.

READ THIS FIRST
---------------
Every number this module produces is SYNTHETIC. No API is called and no real
model output is shipped in this repository. The simulator exists so that the
audit metrics in `metrics.py` can be demonstrated deterministically, offline, on
a laptop with no keys and no network -- and so that anyone can re-run the talk's
figures and get the same numbers.

The simulator's parameters are *calibrated* to effect sizes that published work
reports for real judges, so the demo's shape is honest even though its data is
not real. Each default below cites the source it was set from. See
`docs/calibration.md` for the full table, and swap in your own numbers freely:
that is the point of the exercise, not the specific values.

The one thing this module must never be used for is a claim about a specific
real model. If you want numbers about your judge, run `metrics.py` on your
judge's own trace (`docs/using-your-own-data.md`).
"""

from __future__ import annotations

from dataclasses import dataclass, asdict

import numpy as np
import pandas as pd

SYNTHETIC_NOTICE = (
    "SYNTHETIC DATA -- generated by judge_audit.simulate, calibrated to published "
    "effect sizes. Not the output of any real model."
)


@dataclass
class JudgeProfile:
    """Everything that can be wrong with a judge, as knobs.

    Defaults describe a plausible frontier hosted judge on a moderately
    ambiguous multimodal task -- roughly the regime where a team has decided the
    judge is "good enough to automate" and stopped checking.
    """

    name: str = "hosted-judge-v1"

    # --- run-to-run instability -------------------------------------------- #
    # Repeated scoring of identical input disagrees. Haldar et al. (EMNLP 2025)
    # find all-run-identical verdicts on only 61.3% of cases for one judge;
    # Lau et al. (2026) find score variability even at temperature 0.
    noise_floor: float = 0.15          # SD in points on easy, unambiguous items
    noise_slope: float = 1.60          # extra SD at maximum ambiguity

    # --- central-tendency compression --------------------------------------- #
    # When a judge cannot tell, it does not say so: it regresses toward a safe
    # middling score. Li et al. (DASFAA 2026) and Fujinuma et al. (ACL 2026)
    # document this scale-use pathology. It is the mechanism that makes a
    # recovered blank *look* like a measurement while carrying almost no signal.
    central_pull: float = 0.95         # weight on the safe score at max ambiguity
    central_score: float = 6.5

    # --- silent dropout ----------------------------------------------------- #
    # Blank / unparseable / refused outputs, concentrated on ambiguous items.
    blank_intercept: float = -5.60     # logit of blanking an easy item
    blank_slope: float = 9.00          # extra logit at maximum ambiguity
    retry_attempts: int = 3            # a retry-on-blank loop, as any sane harness has

    # --- style over substance ----------------------------------------------- #
    # Feuer et al. (ICLR 2025): judge preference tracks style, not correctness.
    # Verbosity slope is signed differently per model family (Soumik, TMLR 2026).
    verbosity_coef: float = 0.30       # judge points per SD of response length
    fluent_wrong_inflation: float = 2.80   # points a confident wrong answer gains

    # --- scale-use pathology ------------------------------------------------ #
    # Fujinuma et al. (ACL 2026), Li et al. (DASFAA 2026): judges cluster on a
    # few values and are sensitive to the declared range.
    anchor_scores: tuple[int, ...] = (5, 7, 8)
    anchor_pull: float = 0.10          # probability a score snaps to an anchor

    # --- position bias ------------------------------------------------------ #
    # Zheng et al. (2023) Table 2: position consistency 65.0% (GPT-4),
    # 23.8% (Claude-v1). Shi et al. (2025): flips concentrate on close pairs.
    first_position_preference: float = 0.62   # P(prefer first) on a dead-heat pair
    pair_discrimination: float = 6.0          # how sharply real quality gaps win out

    # --- the binary semantic-equivalence judge ------------------------------ #
    equiv_sensitivity: float = 0.93    # P(says "equivalent" | it really is)
    equiv_specificity: float = 0.84    # P(says "not equivalent" | it really isn't)

    def to_row(self) -> dict:
        d = asdict(self)
        d["anchor_scores"] = ",".join(str(s) for s in self.anchor_scores)
        return d


# A deliberately better-behaved judge, for the "so what do I do" half of the talk.
CAREFUL_PROFILE = JudgeProfile(
    name="audited-judge-v2",
    noise_floor=0.12,
    noise_slope=0.55,          # rubric + reference answer cuts ambiguity noise
    blank_intercept=-6.20,
    blank_slope=4.00,
    retry_attempts=3,
    verbosity_coef=0.08,
    fluent_wrong_inflation=0.90,
    anchor_pull=0.05,
    central_pull=0.35,
    first_position_preference=0.52,
    pair_discrimination=9.0,
    equiv_sensitivity=0.95,
    equiv_specificity=0.91,
)


def _sigmoid(x: np.ndarray | float) -> np.ndarray | float:
    return 1.0 / (1.0 + np.exp(-x))


def make_items(
    n: int = 600,
    *,
    seed: int = 20260911,
    fluent_wrong_share: float = 0.15,
    human_noise: float = 0.75,
    systems: tuple[str, str] = ("model-A", "model-B"),
    system_quality_gap: float = 0.020,
) -> pd.DataFrame:
    """The evaluation set: latent quality, human reference, and item metadata.

    `fluent_wrong_share` are the items that matter most in a legally grounded
    task: the response reads well, is confidently phrased, and says the wrong
    thing. Human reference marks them incorrect; a graded style judge will not.
    """
    rng = np.random.default_rng(seed)

    half = n // 2
    system = np.array([systems[0]] * half + [systems[1]] * (n - half))
    base_quality = rng.beta(5.0, 2.6, size=n)
    quality = np.clip(
        base_quality + np.where(system == systems[0], system_quality_gap, -system_quality_gap),
        0.02, 0.98,
    )

    # Ambiguity is a property of the *item and response*, not of its quality: a
    # cluttered image, a partially occluded sign, a response that hedges two
    # readings. It is mostly independent of how good the answer is, with a mild
    # pull toward mid-quality items. Keeping the two apart matters, because if
    # ambiguity were just "mid quality" then dropping ambiguous items would only
    # restrict the score range, and the survivorship effect in the demo would be
    # an artefact of that restriction rather than of the judge's behaviour.
    intrinsic = rng.beta(2.0, 3.0, size=n)
    ambiguity = 0.88 * intrinsic + 0.12 * (1.0 - np.abs(2 * quality - 1.0))
    ambiguity = (ambiguity - ambiguity.min()) / (ambiguity.max() - ambiguity.min())

    fluent_wrong = rng.random(n) < fluent_wrong_share
    # Response length is only loosely tied to quality, and fluent-wrong answers
    # are longer than average -- that is what makes them fool a style judge.
    response_tokens = np.clip(
        rng.normal(220 + 60 * quality + 110 * fluent_wrong, 55), 40, None
    ).round()

    # Two separate human judgements, because they are two separate questions.
    # `human_score` is graded response quality -- how well written, how helpful.
    # A fluent-but-wrong answer scores *well* here, which is the whole problem.
    # `human_correct` is semantic agreement with the legal reference: does this
    # response mean what the reference means? A fluent-but-wrong answer fails it.
    human_score = np.clip(
        np.round(10 * quality + 0.8 * fluent_wrong + rng.normal(0, human_noise, n)), 0, 10
    )
    human_correct = (quality >= 0.62) & (~fluent_wrong)

    # Quartiles of ambiguity, so every stratum has the same number of items and
    # a per-stratum correlation is comparable across strata by construction.
    strata = pd.qcut(
        ambiguity, 4, labels=["Q1 clearest", "Q2", "Q3", "Q4 most ambiguous"]
    )

    return pd.DataFrame(
        {
            "item_id": [f"it{i:04d}" for i in range(n)],
            "system": system,
            "latent_quality": quality.round(4),
            "ambiguity": ambiguity.round(4),
            "difficulty_stratum": strata,
            "fluent_but_wrong": fluent_wrong,
            "response_tokens": response_tokens.astype(int),
            "human_score": human_score,
            "human_correct": human_correct,
            "_note": SYNTHETIC_NOTICE,
        }
    )


def _score_once(
    items: pd.DataFrame,
    profile: JudgeProfile,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    """One judging pass. Returns (scores with NaN for blanks, blank mask)."""
    n = len(items)
    q = items["latent_quality"].to_numpy()
    amb = items["ambiguity"].to_numpy()
    fw = items["fluent_but_wrong"].to_numpy()
    toks = items["response_tokens"].to_numpy(float)
    length_z = (toks - toks.mean()) / toks.std()

    signal = (
        10 * q
        + profile.verbosity_coef * length_z
        + profile.fluent_wrong_inflation * fw
    )
    # The harder the item, the more the judge falls back on a safe middling
    # score instead of measuring. Same scale, less and less information.
    w = profile.central_pull * amb
    mean = (1 - w) * signal + w * profile.central_score
    sd = profile.noise_floor + profile.noise_slope * amb
    raw = rng.normal(mean, sd)

    scores = np.clip(np.round(raw), 0, 10)

    # Anchoring: a fraction of scores snap to the judge's favourite values.
    anchors = np.array(profile.anchor_scores, dtype=float)
    snap = rng.random(n) < profile.anchor_pull
    nearest = anchors[np.abs(scores[:, None] - anchors[None, :]).argmin(axis=1)]
    scores = np.where(snap, nearest, scores)

    blank_p = _sigmoid(profile.blank_intercept + profile.blank_slope * amb)
    blank = rng.random(n) < blank_p
    scores = np.where(blank, np.nan, scores)
    return scores, blank


def run_judge(
    items: pd.DataFrame,
    profile: JudgeProfile | None = None,
    *,
    n_runs: int = 3,
    seed: int = 7,
) -> pd.DataFrame:
    """Score every item `n_runs` times, as if the harness were re-run.

    Produces both the raw column (`judge_score`, blanks left blank -- this is
    what a single pass gives you) and a recovered column
    (`judge_score_recovered`, blanks retried up to `profile.retry_attempts`
    times). The gap between correlations computed on those two columns is the
    survivorship effect the talk is built around.
    """
    profile = profile or JudgeProfile()
    rng = np.random.default_rng(seed)
    frames = []

    for run in range(1, n_runs + 1):
        scores, blank = _score_once(items, profile, rng)

        recovered = scores.copy()
        for _ in range(profile.retry_attempts):
            todo = np.isnan(recovered)
            if not todo.any():
                break
            retry, _ = _score_once(items, profile, rng)
            recovered = np.where(todo, retry, recovered)

        eq_truth = items["human_correct"].to_numpy()
        u = rng.random(len(items))
        equivalent = np.where(
            eq_truth,
            u < profile.equiv_sensitivity,
            u > profile.equiv_specificity,
        )

        frames.append(
            pd.DataFrame(
                {
                    "item_id": items["item_id"].to_numpy(),
                    "run": run,
                    "judge": profile.name,
                    "judge_score": scores,
                    "judge_score_recovered": recovered,
                    "was_blank": blank,
                    "equivalent": equivalent,
                }
            )
        )

    trace = pd.concat(frames, ignore_index=True)
    cols = [
        "item_id", "system", "latent_quality", "ambiguity", "difficulty_stratum",
        "fluent_but_wrong", "response_tokens", "human_score", "human_correct",
    ]
    return trace.merge(items[cols], on="item_id", how="left")


def make_pairs(
    items: pd.DataFrame,
    profile: JudgeProfile | None = None,
    *,
    n_pairs: int = 300,
    seed: int = 11,
) -> pd.DataFrame:
    """Pairwise comparisons, each judged in both orders.

    The judge sees (A, B) and then (B, A). A judge that is measuring anything
    picks the same winner both times. `winner_ab` / `winner_ba` are recorded as
    the *candidate* that won, so equality across the two columns means the
    verdict survived the swap.
    """
    profile = profile or JudgeProfile()
    rng = np.random.default_rng(seed)
    idx_a = rng.integers(0, len(items), n_pairs)
    idx_b = rng.integers(0, len(items), n_pairs)
    keep = idx_a != idx_b
    idx_a, idx_b = idx_a[keep], idx_b[keep]

    qa = items["latent_quality"].to_numpy()[idx_a]
    qb = items["latent_quality"].to_numpy()[idx_b]
    gap = qa - qb

    # P(pick the candidate shown first) = position preference on a dead heat,
    # pulled toward the genuinely better answer as the quality gap widens.
    def pick(first_is_a: bool) -> np.ndarray:
        signed_gap = gap if first_is_a else -gap
        logit = (
            np.log(profile.first_position_preference / (1 - profile.first_position_preference))
            + profile.pair_discrimination * signed_gap
        )
        first_wins = rng.random(len(gap)) < _sigmoid(logit)
        if first_is_a:
            return np.where(first_wins, "A", "B")
        return np.where(first_wins, "B", "A")

    return pd.DataFrame(
        {
            "pair_id": [f"pr{i:04d}" for i in range(len(gap))],
            "item_a": items["item_id"].to_numpy()[idx_a],
            "item_b": items["item_id"].to_numpy()[idx_b],
            "quality_gap": gap.round(4),
            "true_winner": np.where(gap > 0, "A", "B"),
            "winner_ab": pick(True),
            "winner_ba": pick(False),
        }
    )


def build_dataset(
    *,
    n_items: int = 600,
    n_runs: int = 3,
    profile: JudgeProfile | None = None,
    seed: int = 20260911,
) -> dict[str, pd.DataFrame]:
    """One call that produces everything the demo and the figures need."""
    items = make_items(n_items, seed=seed)
    trace = run_judge(items, profile, n_runs=n_runs, seed=seed + 1)
    pairs = make_pairs(items, profile, seed=seed + 2)

    # Per-item view: mean recovered score, majority equivalence verdict.
    per_item = (
        trace.groupby("item_id")
        .agg(
            graded_score=("judge_score_recovered", "mean"),
            graded_single_run=("judge_score", "first"),
            equivalent=("equivalent", lambda s: bool(s.mean() >= 0.5)),
        )
        .reset_index()
        .merge(items, on="item_id", how="left")
    )
    return {"items": items, "trace": trace, "pairs": pairs, "per_item": per_item}
